/**
 * Build-time content encryption.
 *
 * Reads the plan content from src/data/contents.js, encrypts it with
 * AES-256-GCM using a key derived from the configured password via
 * PBKDF2-SHA256 (600,000 iterations, per OWASP 2024+ guidance), and
 * writes a self-contained encrypted payload module to src/data/__payload.js.
 *
 * The deployed bundle contains ONLY the ciphertext + parameters needed to
 * decrypt. The password never enters the bundle. Without the password the
 * content is mathematically unrecoverable.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { randomBytes, pbkdf2Sync, createCipheriv } from 'node:crypto';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, '..');

const PASSWORD_FILE = resolve(ROOT, '.password.json');
const CONTENTS_FILE = resolve(ROOT, 'content-source/contents.js');
const OUT_FILE = resolve(ROOT, 'src/data/__payload.js');

const PBKDF2_ITERATIONS = 600_000;
const KEY_LENGTH = 32; // 256-bit
const SALT_LENGTH = 16; // 128-bit
const IV_LENGTH = 12; // 96-bit, recommended for GCM

function readPassword() {
  if (!existsSync(PASSWORD_FILE)) {
    console.error(
      '\n❌ Missing .password.json at project root.\n' +
        '   Create it with the shape: { "password": "your-password" }\n'
    );
    process.exit(1);
  }
  const raw = JSON.parse(readFileSync(PASSWORD_FILE, 'utf8'));
  if (!raw.password || typeof raw.password !== 'string' || raw.password.length < 8) {
    console.error('\n❌ Password in .password.json is missing or too short (min 8 chars).\n');
    process.exit(1);
  }
  return raw.password;
}

async function loadContents() {
  // Dynamic ESM import of the contents module
  const url = pathToFileURL(CONTENTS_FILE).href + `?t=${Date.now()}`;
  const mod = await import(url);
  if (!mod.contents) {
    console.error('\n❌ src/data/contents.js must export `contents`.\n');
    process.exit(1);
  }
  return mod.contents;
}

function encrypt(plaintext, password) {
  const salt = randomBytes(SALT_LENGTH);
  const iv = randomBytes(IV_LENGTH);
  const key = pbkdf2Sync(password, salt, PBKDF2_ITERATIONS, KEY_LENGTH, 'sha256');

  const cipher = createCipheriv('aes-256-gcm', key, iv);
  const ciphertext = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
  const authTag = cipher.getAuthTag();

  return {
    v: 1,
    alg: 'AES-256-GCM',
    kdf: 'PBKDF2-SHA256',
    iter: PBKDF2_ITERATIONS,
    salt: salt.toString('base64'),
    iv: iv.toString('base64'),
    tag: authTag.toString('base64'),
    data: ciphertext.toString('base64'),
  };
}

async function main() {
  const start = Date.now();
  console.log('🔒 Encrypting plan content...');

  const password = readPassword();
  const contents = await loadContents();
  const json = JSON.stringify(contents);
  const sizeKB = (Buffer.byteLength(json, 'utf8') / 1024).toFixed(1);

  const payload = encrypt(json, password);

  const moduleSource = `// AUTO-GENERATED by scripts/encrypt-content.mjs — do not edit by hand.
// This file holds the AES-256-GCM ciphertext of the dashboard content.
// Without the password, this is unrecoverable. Built at ${new Date().toISOString()}.
export const payload = ${JSON.stringify(payload, null, 2)};
`;

  writeFileSync(OUT_FILE, moduleSource, 'utf8');

  const ms = Date.now() - start;
  console.log(`✅ Encrypted ${sizeKB} KB of plan content in ${ms}ms`);
  console.log(`   → ${OUT_FILE}`);
}

main().catch((err) => {
  console.error('❌ Encryption failed:', err);
  process.exit(1);
});
